package vn.iotstar.controller;
import jakarta.validation.Valid; import lombok.RequiredArgsConstructor; import org.springframework.data.domain.PageRequest; import org.springframework.security.core.Authentication; import org.springframework.stereotype.Controller; import org.springframework.ui.Model; import org.springframework.validation.BindingResult; import org.springframework.web.bind.annotation.*; import org.springframework.web.multipart.MultipartFile; import vn.iotstar.dto.ProductDTO; import vn.iotstar.entity.Product; import vn.iotstar.repository.*; import vn.iotstar.service.CloudinaryService;
@Controller @RequiredArgsConstructor public class ProductController {
 private final ProductRepository products; private final CategoryRepository cats; private final UserRepository users; private final CloudinaryService cloud;
 @GetMapping("/products") String list(@RequestParam(defaultValue="") String q,@RequestParam(defaultValue="0") int page,Model m){m.addAttribute("products",products.findByNameContainingIgnoreCaseOrDescriptionContainingIgnoreCase(q,q,PageRequest.of(Math.max(0,page),10)));m.addAttribute("q",q);return "products/list";}
 @GetMapping("/products/new") String form(Model m){m.addAttribute("form",new ProductDTO());m.addAttribute("categories",cats.findAll());return "products/form";}
 @GetMapping("/products/edit/{id}") String edit(@PathVariable Long id,Model m){var p=products.findById(id).orElseThrow();var dto=new ProductDTO(p.getId(),p.getName(),p.getPrice(),p.getDescription(),p.getImageUrl(),p.getCategory().getId(),p.getCategory().getName());m.addAttribute("form",dto);m.addAttribute("categories",cats.findAll());return "products/form";}
 @PostMapping("/products/save") String save(@Valid @ModelAttribute("form") ProductDTO dto,BindingResult br,@RequestParam(required=false) MultipartFile image,Authentication auth,Model m){if(br.hasErrors()){m.addAttribute("categories",cats.findAll());return "products/form";}var u=users.findByEmailIgnoreCase(auth.getName()).orElseThrow();Product p=dto.getId()==null?new Product():products.findById(dto.getId()).orElseThrow();p.setName(dto.getName());p.setPrice(dto.getPrice());p.setDescription(dto.getDescription());p.setCategory(cats.findById(dto.getCategoryId()).orElseThrow());if(p.getId()==null)p.setUser(u);if(image!=null&&!image.isEmpty())p.setImageUrl(cloud.upload(image));products.save(p);return "redirect:/products";}
 @PostMapping("/products/delete/{id}") String delete(@PathVariable Long id){products.deleteById(id);return "redirect:/products";}
}
